name: insights

on: push

defaults:
  run:
    working-directory: src

jobs:
  phpinsights:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      
    - name: Install PHPInsights
      run: composer require nunomaduro/phpinsights --dev --no-progress --no-ansi --no-interaction

    - name: phpinsights
      run: php artisan insights -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80
