name: insights

on: push

defaults:
  run:
    working-directory: src

jobs:
  phpinsights:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: phpinsights
      uses: stefanzweifel/laravel-phpinsights-action@v1.0.0
      with:
        args: -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80
