name: insights

on: push

defaults:
  run:
    working-directory: src

jobs:
  phpinsights:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
        coverage: none

    - name: Composer dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      
    - name: Install PHPInsights
      run: composer require nunomaduro/phpinsights --dev --no-progress --no-ansi --no-interaction
      
    - name: Publish config
      run: php artisan vendor:publish --provider="NunoMaduro\PhpInsights\Application\Adapters\Laravel\InsightsServiceProvider"

    - name: Run PHPInsights
      run: php artisan insights -v --min-quality=80 --min-complexity=80 --min-architecture=80 --min-style=80
