# This is a basic workflow to help you get started with Actions

name: PHPInsights

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: src

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  phpinsights:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Displaying current folder
      run: ls -lah

    - uses: MilesChou/composer-action@master
      with:
        args: install --no-interaction --no-scripts --no-suggest --prefer-dist

    - uses: stefanzweifel/laravel-phpinsights-action@v1.1.1
