name: PHPUnit

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: src

jobs:

  tests:
    runs-on: ubuntu-latest
    name: PHPUnit

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Copy ENV Laravel Configuration for CI
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
        
      - name: Generate key
        run: php artisan key:generate
      
      - name: Create DB and schemas
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate:fresh --seed
        
      - name: Install NPM dependencies
        run: npm install
        
      - name: Compile assets
        run: npm run production
        
      - name: Execute tests
        run: vendor/bin/phpunit --verbose
