name: phpunit

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: src

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          
      - name: Run PHPUnit
        run: vendor/bin/phpunit tests/
